---
title: "Siagro+"
---
# Estadisticas de la actividad agropecuaria, desarrollo rural, seguridad alimentaria y nutricional y cambio climático de Centroamérica y México
El Sistema de Información Agropecuaria (SIAGRO) contiene información de variables de la actividad agropecuaria, desarrollo rural, seguridad alimentaria y variables climáticas. Considera once países en su cobertura geográfica: Belice, Costa Rica, Cuba, El Salvador, Guatemala, Haití, Honduras, México, Nicaragua, Panamá y República Dominicana, y contiene datos anuales y mensuales. 
SIAGRO es impulsado por la Unidad de Desarrollo Agrícola y Cambio Climático en la Sede Subregional en México de la CEPAL. La información se origina en la CEPAL o en otras bases de datos de agencias asociadas, y cada indicador tiene una explicación de su fuente y metadatos.


# Statistics on agricultural activity, rural development, food and nutritional security and climate change in Central America and Mexico 
The Agricultural Information System (SIAGRO) contains information on agricultural activity, rural development, food security and climate variables. It covers eleven countries: Belize, Costa Rica, Cuba, The Dominican Republic, El Salvador, Guatemala, Haiti, Honduras, Mexico, Nicaragua and Panama, and contains annual and monthly data.
SIAGRO is maintained by the Agricultural Development and Climate Change Unit at ECLAC's Subregional Headquarters in Mexico. The information originates from either ECLAC or other partner agency databases, and each indicator comes with an explanation of its source and metadata.


